### ISSUE TITLE
Create pydantic models

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVSiteAPI#1]
## Detailed Description
Pydantic models

## Context
Need so we know what is returned in the API

### one_pv_actual
Client sends data to us, and we save to database
Post to us
Input Schema
- site_uuid
- datetime_utc
- actual_generation_kw

### multiple_pv_actual
Get the client pv data front the past
Parameters
- site_uuid (list)
Schema (list)
- site_uuid
- actual_values (list)
    - datetime_utc
    - actual_generation_kw

### forecast
Client gets the forecast for their site
Parameters
Site_uuid (list)

Schema
- forecast_metadata_uuid
- forecast_value (list)
    - target_datetime_utc
    - expected_generation_kw

### forecast_metadata
Get the when the forecast is made, what site is, forecast version
Schema
- forecast_metadata_uuid
- site_uuid
- forecast_creation_time
- forecast_version

###  sites
Clients get the site id that are available to them
Schema (list)
- site_uuid
- site_name
- latitude 
- longitude
- capacity_kw

### status
Same as nowcasting - /v0/solar/GB/status
see https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/models/models.py#L125

**Comment by rachel-labri-tipton** [comment]
hey @peterdudfield, I pushed my initial class schemas to the main branch here. I have a couple questions about how to handle lists in these classes. maybe something to look at briefly in our one-to-one today or we can schedule another API chat.

**Comment by peterdudfield** [comment]
I saw you updated it - https://github.com/openclimatefix/PVSiteAPI/blob/main/pydantic_models.py#L68
i think you can do
```
site_list: [PV_Site_Metadata] = Field(..., description="List of all sites with their metadata")
```
to keep it tidy
